[package]
name = "tokio-exec"
version = "0.1.0"
edition = "2024"

[dependencies]
mylib = {path = "../mylib", default-features = false, features = [ "async", "sync" ] }
tokio = {version = "1.45.1", features = [ "full" ] }
